### ISSUE TITLE
When will source code be released?

### ISSUE THREAD

**Issue by luisfredgs** [StonyBrookNLP/deformer#1]
Hello. When will source code be released? I'm very interested in this implementation.

**Comment by csarron** [comment]
Thanks for the interest, we are preparing the codebase and verify the results we reported, I'd say it will be out soon, definitely before the conference. Stay tuned.

**Comment by luisfredgs** [comment]
Thanks for replying!

**Comment by underspirit** [comment]
the conference is coming soon.

**Comment by csarron** [comment]
Thank you all! Just added a working version. Please feel free to check
