### ISSUE TITLE
运行bug

### ISSUE THREAD

**Issue by Vincent131499** [StonyBrookNLP/deformer#4]
1.生成训练和评估数据提示：没有找到‘tokenizers’这个模块，具体可见‘features/feature_bert_classify.py’第一行。

2.该代码是在什么环境下训练的，TPU还是GPU？

**Comment by csarron** [comment]
Hi @Vincent131499, did you follow the installation instructions: `pip install -r requirements.txt`. The `tokenizers` library along with other dependency libraries should be installed first.

The models are fine-tuned using TPUs, it should also work on GPUs (but not verified).

**Comment by sc1054** [comment]
@csarron   Can you verify it in GPUs？I found a bug "Restoring from the checkpoint failed" even though logger print "INIT FROM CKPT*"  in line 114 of file "common/builder.py".

**Comment by csarron** [comment]
@sc1054 can you elaborate on which script/command caused the failure on GPU?

**Comment by sc1054** [comment]
@csarron I trained on my own data set through the "train.py" with the parameters of the qqp task. I named qqp task. Actually, when I change the _replace_map_ to **_{'LayerNorm': 'layer_norm', 'bert/': 'bert_classififier/bert/'}_** in classifier_bert.py, the bug disappeared. I used tensorflow-gpu==1.15.0
