### ISSUE TITLE
What is bert_model.ckpt file?

### ISSUE THREAD

**Issue by Woffee** [StonyBrookNLP/deformer#8]
Hello, when I ran `eval.py`, I got an error:
```
Failed to get matching files on ./data/ckpt/init/uncased_base/bert_model.ckpt
``` 

So, what is the `bert_model.ckpt` file, and can you tell me how to get it? 
Thank you!

**Comment by csarron** [comment]
Hi @Woffee , please follow https://github.com/StonyBrookNLP/deformer#squad-11-quickstart to download the fine-tuned checkpoint if you just want to run the SQuAD evaluation. If you want to do the fine-tuning, you need to download the original BERT checkpoint.

**Comment by winston52** [comment]
Hello, I followed the instruction and downloaded checkpoint file , the file's path is 

> ./deformer/data/ckpt/bert-base/squad_v1.1/

 and when I ran commond  **python eval.py -m bert -t squad_v1.1 2>&1 | tee data/bert-base-eval.log** , I still got the same error...

> Failed to get matching files on ./deformer/data/ckpt/init/uncased_base/bert_model.ckpt

maybe there something wrong in path's setting?  I still don't know how to get the 'bert_model.ckpt' file.

sorry for this stupid question...

thanks and hope for your response

**Comment by winston52** [comment]
I download the orginal bert base file and put it in path

>  deformer/data/ckpt/init/uncased_base/

then the problem has been solved

thanks!
